import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ClientProvider from "./clientProvider";
import TopBar from "@/ui-components/TopBar";
import SpeedComponent from "@/ui-components/SpeedComponent";
const inter = Inter({ subsets: ["latin"] });
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import SlidingMenu from "../ui-components/SlidingMenu";
import { getUserTheme } from "@/api/theme/show";

export const metadata: Metadata = {
  title: "Chata GJKT",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const theme = await getUserTheme();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          {/* OMG 100dvh works like a charms!  f*/}
          <div className="flex flex-col" style={{ height: "100dvh" }}>
            <ClientProvider theme={theme}>
              <TopBar />
              <SlidingMenu userRole={"admin"} />
              <SpeedComponent />
              <div className="py-2 overflow-auto flex-grow">{children}</div>
            </ClientProvider>
          </div>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
