name: Ping Supabase to Prevent Pausing

on:
  schedule:
    - cron: '0 9 * * 1,4'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Supabase Client
        run: npm install @supabase/supabase-js --force

      - name: Ping Supabase
        env:
          SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: |
          node -e "
          const { createClient } = require('@supabase/supabase-js');
          
          (async () => {
            try {
              const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);
              
              const { data, error } = await supabase.storage.listBuckets();
              
              if (error) {
                console.error('Error pinging Supabase:', error);
                process.exit(1);
              }
              
              console.log('Successfully pinged Supabase. Found', data.length, 'buckets');
            } catch (err) {
              console.error('Failed to ping Supabase:', err);
              process.exit(1);
            }
          })();
          "